Repository Automattic/vip-go-nextjs-skeleton, pull requests merged in 2022-01, with the labels that each got.

#49 Added html img component instad of next/image when using srcSet
  .eslintrc
  components/PostContent/PostContent.tsx
  next.config.js
  vip.config.js
Labels: [Status] Ready to Merge

#51 Add support for innerBlocks
  README.md
  components/UnsupportedBlock/UnsupportedBlock.tsx
  graphql/fragments/ContentBlock.graphql
  graphql/fragments/ContentNode.graphql
Labels: [Status] Needs Review

#52 Demonstrate supporting a new block
  components/PostContent/PostContent.tsx
  components/Quote/Quote.module.css
  components/Quote/Quote.tsx
Labels: [Type] Enhancement, [Status] Needs Review, [Pri] Low, Good First Issue
